package com.filamentbarbaner.service;

import com.filamentbarbaner.dto.MenuItemDto;
import com.filamentbarbaner.model.MenuItem;
import com.filamentbarbaner.model.MenuItemCategory;
import com.filamentbarbaner.repository.MenuItemRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class MenuService {

    private final MenuItemRepository menuItemRepository;

    public MenuService(MenuItemRepository menuItemRepository) {
        this.menuItemRepository = menuItemRepository;
    }

    private MenuItemDto toDto(MenuItem menuItem) {
        return new MenuItemDto(
            menuItem.getId(),
            menuItem.getName(),
            menuItem.getDescription(),
            menuItem.getPrice(),
            menuItem.getCategory(),
            menuItem.getImageUrl(),
            menuItem.isAvailable()
        );
    }

    private MenuItem toEntity(MenuItemDto menuItemDto) {
        MenuItem menuItem = new MenuItem();
        // ID is not set here as it's generated by the database for new entities.
        // For updates, an existing entity is fetched and its fields are updated.
        menuItem.setName(menuItemDto.name());
        menuItem.setDescription(menuItemDto.description());
        menuItem.setPrice(menuItemDto.price());
        menuItem.setCategory(menuItemDto.category());
        menuItem.setImageUrl(menuItemDto.imageUrl());
        menuItem.setAvailable(menuItemDto.isAvailable());
        return menuItem;
    }

    public List<MenuItemDto> getAllMenuItems(Optional<MenuItemCategory> category) {
        List<MenuItem> menuItems;
        if (category.isPresent()) {
            menuItems = menuItemRepository.findByCategory(category.get());
        } else {
            menuItems = menuItemRepository.findAll();
        }
        return menuItems.stream()
            .map(this::toDto)
            .collect(Collectors.toList());
    }

    public MenuItemDto createMenuItem(MenuItemDto menuItemDto) {
        MenuItem newMenuItem = toEntity(menuItemDto);
        // The toEntity method does not set the ID, ensuring it's generated by the DB.
        MenuItem savedMenuItem = menuItemRepository.save(newMenuItem);
        return toDto(savedMenuItem);
    }

    public Optional<MenuItemDto> updateMenuItem(UUID id, MenuItemDto menuItemDto) {
        return menuItemRepository.findById(id)
            .map(existingMenuItem -> {
                existingMenuItem.setName(menuItemDto.name());
                existingMenuItem.setDescription(menuItemDto.description());
                existingMenuItem.setPrice(menuItemDto.price());
                existingMenuItem.setCategory(menuItemDto.category());
                existingMenuItem.setImageUrl(menuItemDto.imageUrl());
                existingMenuItem.setAvailable(menuItemDto.isAvailable());
                MenuItem updatedMenuItem = menuItemRepository.save(existingMenuItem);
                return toDto(updatedMenuItem);
            });
    }

    public void deleteMenuItem(UUID id) {
        menuItemRepository.deleteById(id);
    }
}